export default {
  bodyEl: document.querySelector('body'),
  mainEl: document.querySelector('main'),
  sliderEl: document.querySelector('.js-slider'),
  paginationEl: document.querySelector('#pagination'),
  gallery: document.querySelector('.trending'),
  galleryEl: document.querySelector('.gallery'),
  backdropEl: document.querySelector('.backdrop'),
  inputField: document.querySelector('.search-form__input'),
  formEl: document.querySelector('.search-form-js'),
  modalFilmEl: document.getElementById('modal-film'),
  modalFilmImageEl: document.getElementById('modal-film-image'),
  modalFilmDescriptionEl: document.getElementById('modal-film-description'),
  buttonWatchedEl: document.querySelector('[data-value="watched"]'),
  buttonQueveEl: document.querySelector('[data-value="queve"]'),
  checkboxEl: document.querySelector('.theme-switch__toggle'),
  buttonCloseIconEl: document.querySelector('.button-close__icon'),
};
