export default {
  bodyEl: document.querySelector('body'),
  mainEl: document.querySelector('main'),
  sliderEl: document.querySelector('.js-slider'),
  paginationEl: document.querySelector('#pagination'),
  gallery: document.querySelector('.trending'),
  library: document.querySelector('.library'),
  buttonLibrary: document.querySelector('.library-button'),
  galleryEl: document.querySelector('.gallery'),
  backdropEl: document.querySelector('.backdrop'),
  inputField: document.querySelector('.search-form__input'),
  formEl: document.querySelector('.search-form-js'),
  modalFilmEl: document.getElementById('modal-film'),
  modalFilmImageEl: document.getElementById('modal-film-image'),
  modalFilmDescriptionEl: document.getElementById('modal-film-description'),
  buttonWatchedEl: document.querySelector('.watched-js'),
  buttonQueveEl: document.querySelector('.queue-js'),
  headerEl: document.querySelector('.header'),
  libraryBtnListEl: document.querySelector('.button-list'),
};
